// master reducer
export const SET_SIDEBAR_OPEN = 'SET_SIDEBAR_OPEN'
export const SET_LOADER_DISPLAY = 'SET_LOADER_DISPLAY'

// Users Type
export const SET_WALLET = 'SET_WALLET'
export const SET_DISPLAY_WALLET = 'SET_DISPLAY_WALLET'
export const SET_WALLET_CONNECTION_STATUS = 'SET_WALLET_CONNECTION_STATUS'

// Coin Flip Type
export const USER_TOKEN_BALANCE = 'USER_TOKEN_BALANCE'
export const COIN_FLIP_GAME_TABLE_DATA = 'COIN_FLIP_GAME_TABLE_DATA'
