//master reducer
export const SET_SIDEBAR_OPEN = "SET_SIDEBAR_OPEN";

// Users Type
export const SET_WALLET_TYPE = "SET_WALLET_TYPE"
export const SET_WALLET = "SET_WALLET"
export const SET_BINANCE_DISCONNECTED = "SET_BINANCE_DISCONNECTED"
export const SET_METAMASK_DISCONNECTED = "SET_METAMASK_DISCONNECTED"
export const SET_METAMASK_WALLET = "SET_METAMASK_WALLET"
