// master reducer
export const SET_SIDEBAR_OPEN = 'SET_SIDEBAR_OPEN'

// Users Type
export const SET_WALLET = 'SET_WALLET'
export const SET_DISPLAY_WALLET = 'SET_DISPLAY_WALLET'
export const SET_WALLET_CONNECTION_STATUS = 'SET_WALLET_CONNECTION_STATUS'
